<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ssafy.live</groupId>
  <artifactId>di</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
  	<maven.compiler.release>21</maven.compiler.release>
  </properties>
  <dependencies>
  	<!-- Source: https://mvnrepository.com/artifact/org.springframework/spring-context -->
	<dependency>
	    <groupId>org.springframework</groupId>
	    <artifactId>spring-context</artifactId>
	    <version>6.2.18</version>
	    <scope>compile</scope>
	</dependency>
	<!-- Source: https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter -->
	<dependency>
	    <groupId>org.junit.jupiter</groupId>
	    <artifactId>junit-jupiter</artifactId>
	    <version>6.0.3</version>
	    <scope>test</scope>
	</dependency>
	<!-- Source: https://mvnrepository.com/artifact/org.springframework/spring-test -->
	<dependency>
	    <groupId>org.springframework</groupId>
	    <artifactId>spring-test</artifactId>
	    <version>6.2.18</version>
	    <scope>test</scope>
	</dependency>
  </dependencies>
</project>